# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9999d4a5d10c6153d0e6e93cfe0bb5498ee1950e7e6428853b2cd35c6cbe94a4f947c9c40690c1870735c0805db1d4ee450d41a614a740609a2ecc00837d92f9

test:
  secret_key_base: 1ff65c3c61089415166b65f7df2d15f588292be6f5dedf181480975f79149c485ee49a9efb0348acf3d1a21dbee7af184cf31cea9908b490fb747546769fb3a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
